#!/usr/bin/bash

# Originally based on http://wiki.smartos.org/display/DOC/Allowing+user+CRUD+in+the+global+zone
# Author: hugo@freenode

tcp_max_buf=16777216
udp_max_buf=16777216
#enable_stmf=1
enable_smb=1
#enable_nfs=1

save_us=( /etc/passwd /etc/shadow /etc/group /etc/user_attr \
          /etc/security/policy.conf /etc/security/auth_attr /etc/security/exec_attr \
          /etc/security/prof_attr /etc/pam.conf /var/smb/smbpasswd \
          /var/smb/smbgroup.db /etc/smbautohome /etc/vfstab )

ukeystor="/usbkey/cn-persist"

# this script needs rsync
if [ ! -f /usr/bin/rsync ]; then
    echo please install rsync
    exit 1
fi

case "$1" in
    'start')
    if [[ -n $(/bin/bootparams | grep '^smartos=true') ]]; then
        [[ -n ${tcp_max_buf} ]] && ipadm set-prop -p max_buf=${tcp_max_buf} tcp
        [[ -n ${udp_max_buf} ]] && ipadm set-prop -p max_buf=${udp_max_buf} udp

        # file magic
        for file in ${save_us[*]}
        do
            ukf=${ukeystor}${file}
            rsync -rtpog $ukf $file
            echo "stor->sys: $file"
        done

        mkdir -p ${ukeystor}/svc/
        [ -e /tmp/nfssrv.lock ] && svccfg export -a nfs/server > ${ukeystor}/svc/nfssrv.prop
        [ -e ${ukeystor}/svc/nfssrv.prop ] && svccfg import ${ukeystor}/svc/nfssrv.prop
        touch /tmp/nfssrv.lock

        [ -e /tmp/smbsrv.lock ] && svccfg export -a smb/server > ${ukeystor}/svc/smbsrv.prop
        [ -e ${ukeystor}/svc/smbsrv.prop ] && svccfg import ${ukeystor}/svc/smbsrv.prop
        touch /tmp/smbsrv.lock

        [ -e /tmp/stmf.lock ] && svccfg export -a stmf > ${ukeystor}/svc/stmf.prop
        [ -e ${ukeystor}/svc/stmf.prop ] && svccfg import ${ukeystor}/svc/stmf.prop
        touch /tmp/stmf.lock

        # mount lofs
        mount -F lofs -a

        # enable services
        if [[ -n ${enable_stmf} ]]; then
            svcadm enable system/stmf
            svcadm enable iscsi/target
        fi
        if [[ -n ${enable_smb} ]]; then
            svcadm enable system/idmap
            svcadm enable smb/client
            svcadm enable smb/server
        fi
        if [[ -n ${enable_nfs} ]]; then
            svcadm enable nfs/server
        fi
    fi
    ;;
    'stop')
        for file in ${save_us[*]}
        do
            ukf=${ukeystor}${file}
            if [[ $ukf -ot $file ]]; then
                rsync -Rrtpogu $file $ukeystor
                echo "sys->stor: $file"
            fi
        done
    ;;
esac
