#!/usr/bin/bash

# Originally based on http://wiki.smartos.org/display/DOC/Allowing+user+CRUD+in+the+global+zone
# Author: hugo@freenode

tcp_max_buf=16777216
udp_max_buf=16777216

save_files=( /etc/passwd /etc/shadow /etc/group /etc/user_attr \
          /etc/security/policy.conf /etc/security/auth_attr /etc/security/exec_attr \
          /etc/security/prof_attr /etc/pam.conf /var/smb/smbpasswd \
          /var/smb/smbgroup.db /etc/smbautohome /etc/vfstab )

#save_svccfg=( nfs/server smb/server stmf )

save_svccfg=( smb/server )

#enable_services=( system/stmf iscsi/target \
#                  system/idmap smb/client smb/server \
#                  nfs/server )

enable_services=( system/idmap smb/client smb/server )

ukeystor="/usbkey/cn-persist"

start() {
    if [[ -n $(/bin/bootparams | grep '^smartos=true') ]]; then
        [[ -n ${tcp_max_buf} ]] && ipadm set-prop -p max_buf=${tcp_max_buf} tcp
        [[ -n ${udp_max_buf} ]] && ipadm set-prop -p max_buf=${udp_max_buf} udp

        # file magic
        for file in ${save_files[*]}
        do
            ukf=${ukeystor}${file}
            if [[ -e ${ukf} ]] && ! cmp -s $ukf $file; then
                cp -p $ukf $file
                echo "stor->sys: $file"
            fi
        done

        for svcprop in ${save_svccfg[*]}
        do
            ukp=${ukeystor}/svc/${svcprop//\//.}.prop
            [[ -e ${ukp} ]] && svccfg import ${ukp}
            echo "store->sys: $svcprop"
        done

        # mount lofs
        mount -F lofs -a &> /dev/null

        for service in ${enable_services[*]}
        do
            svcadm enable $service
            echo "enable svc: $service"
        done
    fi
}

stop() {
    for file in ${save_files[*]}
    do
        ukf=${ukeystor}${file}
        if [[ $ukf -ot $file ]]; then
            cp -p $file $ukf
            echo "sys->stor: $file"
        fi
    done

    mkdir -p ${ukeystor}/svc/
    for svcprop in ${save_svccfg[*]}
    do
        tmp=$(mktemp)
        ukp=${ukeystor}/svc/${svcprop//\//.}.prop
        svccfg export -a ${svcprop} > ${tmp}
        if ! cmp -s ${tmp} ${ukp}; then
            cp ${tmp} ${ukp}
            echo "sys->stor: $svcprop"
        fi
        rm ${tmp}
    done
}

case "$1" in
    'start')
        start
    ;;
    'stop')
        stop
    ;;
esac
